# Generated by Django 5.1.4 on 2025-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
