# Generated by Django 5.1.4 on 2025-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qutions", "0002_user_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("answered", "Answered"),
                    ("skipped", "Skipped"),
                    ("not answered", "Not Answered"),
                ],
                default="not answered",
                max_length=20,
            ),
        ),
    ]
